---
- hosts: all
  become: yes
  tasks:
    - name: Ensure NTP is installed.
      apt: 
        name: ntp
        state: present
    - name: Ensure NTP is running.
      systemd: 
        name: ntp
        state: started
        enabled: yes
