---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/password.yaml
  
  tasks:
    - name: Echo the password key which injected into the env.
      shell: echo $MY_PASSWORD
      environment:
        MY_PASSWORD: "{{ my_password }}"
      register: echo_result

    - name: Show the result.
      debug:
        var: echo_result.stdout
