---
- hosts: all
  become: true

  vars_files:
    - vars.yaml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: 
        update_cache: true
        cache_valid_time: 3600

  handlers:
    - name: restart solr
      systemd:
        name: solr
        state: restarted

  tasks:
    - name: Install Java.
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Download Solr.
      get_url:
        url: "https://www.apache.org/dyn/closer.lua/solr/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz?action=download"
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        checksum: "{{ solr_checksum }}"

    - name: Expand Solr.
      unarchive:
        src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        remote_src: true
        creates: "{{ download_dir }}/solr-{{ solr_version }}/README.txt"
    
    - name: Run Solr installation script.
      command: >
        {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr__service.sh
        -i /opt
        -d /var/solr
        -u solr
        -s solr
        -p 8983
        creates={{ solr_dir }}/bin/solr
    
    - name: Ensure Solr is started and enabled at boot.
      systemd:
        name: solr
        state: started
        enabled: true
