---
- name: Install Apache.
  hosts: all
  become: true

  handlers:
    - import_tasks: handlers/apache.yaml

  pre_tasks:
    - debug: var=ansible_os_family
    - name: Load variable files.
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/apache_{{ ansible_os_family }}.yaml"
        - "vars/apache_default.yaml"

  tasks:
    - import_tasks: tasks/apache.yaml
